# Generated by Django 3.2.6 on 2021-08-29 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0002_auto_20210829_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='store_image/'),
        ),
    ]
